export { default as Home } from "./Home";
export { default as Work } from "./Work";
export { default as Writing } from "./Writing";
export { default as About } from "./About";
export { default as NavBar } from "./Shared/Navbar/Navbar";
export { default as Logo } from "./Shared/Navbar/Logo"
export { default as ContactModal } from "./Shared/ContactModal"
export { default as Footer } from "./Shared/Footer"
export { default as WritingCard } from "./../components/Writing/WritingCard"